### ISSUE TITLE
Supertuxkart nintendo switch und 3DS homebrew spiel 🎮

### ISSUE THREAD

**Issue by AlexanderjanSzawarzynski** [noahdossan/lunix#6]
### Discussed in https://github.com/noahdossan/lunix/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **AlexanderjanSzawarzynski** September  2, 2024</sup>
![SuperTuxKart.jpg](https://github.com/user-attachments/assets/c44a48f8-3bef-4498-b759-1082ce92cea9)

</div>

**Comment by noahdossan** [comment]
What?

**Comment by AlexanderjanSzawarzynski** [comment]
[supertux-miyoo-0.2.zip](https://github.com/user-attachments/files/17253652/supertux-miyoo-0.2.zip)
![SuperTux (1)](https://github.com/user-attachments/assets/e596e7ee-4804-4448-b374-366098722e9a)
Spuertux xbox x ps5 homebrew???

**Comment by AlexanderjanSzawarzynski** [comment]
@ethernete @noahdossan  hallo wie geht's euch

**Comment by noahdossan** [comment]
> @ethernete @noahdossan hallo wie geht's euch

No supertuxcart. This is simulation not driving game
